{/* 
    These data will be used by the frontend
    to get and load specific words/alphabets
    to be displayed in the dictionary tab and used in the learn tab
*/}
export const ALPHABET_DICT = [
    { id: 1, category: "Alphabet", word: "A", media: "/aslMedia/alphabet/A.png", directions: "Make a fist with your thumb straight up against the side of your index finger." },
    { id: 2, category: "Alphabet", word: "B", media: "/aslMedia/alphabet/B.png", directions: "Flatten your hand with fingers together and thumb tucked across the palm." },
    { id: 3, category: "Alphabet", word: "C", media: "/aslMedia/alphabet/C.png", directions: "Curve your hand into a C shape, as if gripping a thick glass." },
    { id: 4, category: "Alphabet", word: "D", media: "/aslMedia/alphabet/D.png", directions: "Point your index finger up; touch your thumb to the tips of your middle, ring, and pinky fingers to form a circle." },
    { id: 5, category: "Alphabet", word: "E", media: "/aslMedia/alphabet/E.png", directions: "Tuck all four fingers down and pull your thumb in tight under them (looks like a claw)." },
    { id: 6, category: "Alphabet", word: "F", media: "/aslMedia/alphabet/F.png", directions: "Touch your index finger and thumb together (like an OK sign); keep the other three fingers spread and pointing up." },
    { id: 7, category: "Alphabet", word: "G", media: "/aslMedia/alphabet/G.png", directions: "Point your index finger and thumb sideways, parallel to each other, like you are measuring something tiny." },
    { id: 8, category: "Alphabet", word: "H", media: "/aslMedia/alphabet/H.png", directions: "Point your index and middle fingers sideways together; tuck the rest." },
    { id: 9, category: "Alphabet", word: "I", media: "/aslMedia/alphabet/I.png", directions: "Make a fist but stick your pinky finger straight up." },
    { id: 10, category: "Alphabet", word: "J", media: "/aslMedia/alphabet/J.png", directions: "Start with the \"I\" position and trace a \"J\" curve in the air with your pinky." },
    { id: 11, category: "Alphabet", word: "K", media: "/aslMedia/alphabet/K.png", directions: "Point your index finger up; put your thumb on the middle of your middle finger, which is angled slightly forward." },
    { id: 12, category: "Alphabet", word: "L", media: "/aslMedia/alphabet/L.png", directions: "Make an \"L\" shape with your index finger pointing up and your thumb pointing sideways." },
    { id: 13, category: "Alphabet", word: "M", media: "/aslMedia/alphabet/M.png", directions: "Make a fist and tuck your thumb under your index, middle, and ring fingers." },
    { id: 14, category: "Alphabet", word: "N", media: "/aslMedia/alphabet/N.png", directions: "Make a fist and tuck your thumb under your index and middle fingers." },
    { id: 15, category: "Alphabet", word: "O", media: "/aslMedia/alphabet/O.png", directions: "Touch all your fingertips to your thumb to form a circle." },
    { id: 16, category: "Alphabet", word: "P", media: "/aslMedia/alphabet/P.png", directions: "Like a \"K\", but pointed downward. Index finger points at the floor, thumb on the middle finger." },
    { id: 17, category: "Alphabet", word: "Q", media: "/aslMedia/alphabet/Q.png", directions: "Like a \"G\", but pointed downward. Your index and thumb \"pinch\" toward the floor." },
    { id: 18, category: "Alphabet", word: "R", media: "/aslMedia/alphabet/R.png", directions: "Cross your middle finger over your index finger (like a \"good luck\" gesture)." },
    { id: 19, category: "Alphabet", word: "S", media: "/aslMedia/alphabet/S.png", directions: "Make a solid fist with your thumb tucked across the front of all your fingers." },
    { id: 20, category: "Alphabet", word: "T", media: "/aslMedia/alphabet/T.png", directions: "Make a fist and tuck your thumb between your index and middle finger." },
    { id: 21, category: "Alphabet", word: "U", media: "/aslMedia/alphabet/U.png", directions: "Point your index and middle fingers straight up, pressed together." },
    { id: 22, category: "Alphabet", word: "V", media: "/aslMedia/alphabet/V.png", directions: "Point your index and middle fingers up and spread them apart (like a \"Peace\" sign)." },
    { id: 23, category: "Alphabet", word: "W", media: "/aslMedia/alphabet/W.png", directions: "Point your index, middle, and ring fingers up and spread them out (forming a \"W\")." },
    { id: 24, category: "Alphabet", word: "X", media: "/aslMedia/alphabet/X.png", directions: "Make a fist, then hook your index finger like a pirate's hook." },
    { id: 25, category: "Alphabet", word: "Y", media: "/aslMedia/alphabet/Y.png", directions: "Stick your thumb and pinky out wide; keep the middle three fingers tucked into the palm." },
    { id: 26, category: "Alphabet", word: "Z", media: "/aslMedia/alphabet/Z.png", directions: "Use your index finger to \"draw\" the letter Z in the air." },
]

export const DIGIT_DICT = [
    { id: 1, category: "Digit", word: "0", media: "/aslMedia/digit/0.png", directions: "Touch all your fingertips to the tip of your thumb to form a clear circle." },
    { id: 2, category: "Digit", word: "1", media: "/aslMedia/digit/1.png", directions: "Hold up your index finger; keep the thumb tucked over the other fingers." },
    { id: 3, category: "Digit", word: "2", media: "/aslMedia/digit/2.png", directions: "Hold up your index and middle fingers in a \"V\" shape." },
    { id: 4, category: "Digit", word: "3", media: "/aslMedia/digit/3.png", directions: "Hold up your thumb, index, and middle fingers. (Same as the gesture for \"W\"" },
    { id: 5, category: "Digit", word: "4", media: "/aslMedia/digit/4.png", directions: "Hold up all four fingers (index, middle, ring, pinky) with the thumb tucked across the palm." },
    { id: 6, category: "Digit", word: "5", media: "/aslMedia/digit/5.png", directions: "Hold up all five fingers and spread them." },
    { id: 7, category: "Digit", word: "6", media: "/aslMedia/digit/6.png", directions: "With the palm facing outward, touch the tip of your thumb to the tip of your pinky finger." },
    { id: 8, category: "Digit", word: "7", media: "/aslMedia/digit/7.png", directions: "With the palm facing outward, touch the tip of your thumb to the tip of your ring finger." },
    { id: 9, category: "Digit", word: "8", media: "/aslMedia/digit/8.png", directions: "With the palm facing outward, touch the tip of your thumb to the tip of your middle finger." },
    { id: 10, category: "Digit", word: "9", media: "/aslMedia/digit/9.png", directions: "With the palm facing outward, touch the tip of your thumb to the tip of your index finger (looks like the \"OK\" gesture)." }
]

export const WORD_DICT = [
    {
        id: 1, category: "Actions", words: [
            { id: 1, word: "Accept", media: "/aslMedia/word/Actions/accept.mp4", directions: "To receive or agree to something offered." },
            { id: 2, word: "Action", media: "/aslMedia/word/Actions/action.mp4", directions: "The process of doing something to achieve a goal." },
            { id: 3, word: "Add", media: "/aslMedia/word/Actions/add.mp4", directions: "To join something to something else so as to increase the size or number." },
            { id: 4, word: "Admire", media: "/aslMedia/word/Actions/admire.mp4", directions: "To look at something or someone with pleasure and approval." },
            { id: 5, word: "Affect", media: "/aslMedia/word/Actions/affect.mp4", directions: "To have an influence on or make a change in something." },
            { id: 6, word: "Allow", media: "/aslMedia/word/Actions/allow.mp4", directions: "To give someone permission to do something." },
            { id: 7, word: "Approach", media: "/aslMedia/word/Actions/approach.mp4", directions: "To come near or nearer to something in distance or time." },
            { id: 8, word: "Arrive", media: "/aslMedia/word/Actions/arrive.mp4", directions: "To reach a destination at the end of a journey." },
            { id: 9, word: "Ask", media: "/aslMedia/word/Actions/ask.mp4", directions: "To say something in order to obtain information or an answer." },
            { id: 10, word: "Avoid", media: "/aslMedia/word/Actions/avoid.mp4", directions: "To keep away from or stop oneself from doing something." },
            { id: 11, word: "Believe", media: "/aslMedia/word/Actions/believe.mp4", directions: "To accept that a statement is true or that someone is telling the truth." },
            { id: 12, word: "Eat", media: "/aslMedia/word/Actions/eat.mp4", directions: "To put food into the mouth and swallow it." },
            { id: 13, word: "Fall in love", media: "/aslMedia/word/Actions/fall in love.mp4", directions: "To develop a deep romantic attachment to someone." },
            { id: 14, word: "Give", media: "/aslMedia/word/Actions/give.mp4", directions: "To freely transfer the possession of something to someone." },
            { id: 15, word: "Love", media: "/aslMedia/word/Actions/love.mp4", directions: "An intense feeling of deep affection." },
            { id: 16, word: "Pray", media: "/aslMedia/word/Actions/pray.mp4", directions: "To address a solemn request or expression of thanks to a deity." },
            { id: 17, word: "Receive", media: "/aslMedia/word/Actions/recieve.mp4", directions: "To be given, presented with, or paid something." },
            { id: 18, word: "Run", media: "/aslMedia/word/Actions/run.mp4", directions: "To move at a speed faster than a walk." },
            { id: 19, word: "Shower", media: "/aslMedia/word/Actions/shower.mp4", directions: "To wash oneself in a spray of water." },
            { id: 20, word: "Sleep", media: "/aslMedia/word/Actions/sleep.mp4", directions: "A natural state of rest for the body and mind." },
            { id: 21, word: "Wake up", media: "/aslMedia/word/Actions/wake up.mp4", directions: "To emerge or cause to emerge from sleep." },
            { id: 22, word: "Walk", media: "/aslMedia/word/Actions/walk.mp4", directions: "To move at a regular pace by lifting and setting down each foot in turn." }
        ]
    },
    {
        id: 2, category: "Adjectives", words: [
            { id: 1, word: "Afraid", media: "/aslMedia/word/Adjectives/afraid.mp4", directions: "Feeling fear or anxiety; frightened." },
            { id: 2, word: "Amazing", media: "/aslMedia/word/Adjectives/amazing.mp4", directions: "Causing great surprise or sudden wonder." },
            { id: 3, word: "Bad", media: "/aslMedia/word/Adjectives/bad.mp4", directions: "Of poor quality or a low standard." },
            { id: 4, word: "Beautiful", media: "/aslMedia/word/Adjectives/beautiful.mp4", directions: "Pleasing the senses or mind aesthetically." },
            { id: 5, word: "Best", media: "/aslMedia/word/Adjectives/best.mp4", directions: "Of the most excellent or desirable type or quality." },
            { id: 6, word: "Better", media: "/aslMedia/word/Adjectives/better.mp4", directions: "Of a higher standard or more appropriate than before." },
            { id: 7, word: "Big", media: "/aslMedia/word/Adjectives/big.mp4", directions: "Of considerable size, extent, or intensity." },
            { id: 8, word: "Cold", media: "/aslMedia/word/Adjectives/cold.mp4", directions: "At a low temperature, especially when compared to the human body." },
            { id: 9, word: "Dumb", media: "/aslMedia/word/Adjectives/dumb.mp4", directions: "Lacking the ability to speak or (informally) acting slow-witted." },
            { id: 10, word: "Fast", media: "/aslMedia/word/Adjectives/fast.mp4", directions: "Moving or capable of moving at high speed." },
            { id: 11, word: "Hot", media: "/aslMedia/word/Adjectives/hot.mp4", directions: "Having a high degree of heat or a high temperature." },
            { id: 12, word: "Long", media: "/aslMedia/word/Adjectives/long.mp4", directions: "Measuring a great distance from end to end." },
            { id: 13, word: "Loud", media: "/aslMedia/word/Adjectives/loud.mp4", directions: "Producing a great deal of volume or noise." },
            { id: 14, word: "Lucky", media: "/aslMedia/word/Adjectives/lucky.mp4", directions: "Having, bringing, or resulting from good fortune." },
            { id: 15, word: "Quiet", media: "/aslMedia/word/Adjectives/quiet.mp4", directions: "Making very little or no noise." },
            { id: 16, word: "See", media: "/aslMedia/word/Adjectives/see.mp4", directions: "To perceive with the eyes; to witness." },
            { id: 17, word: "Short", media: "/aslMedia/word/Adjectives/short.mp4", directions: "Measuring a small distance from end to end or floor to top." },
            { id: 18, word: "Slow", media: "/aslMedia/word/Adjectives/slow.mp4", directions: "Moving or operating at a low speed." },
            { id: 19, word: "Small", media: "/aslMedia/word/Adjectives/small.mp4", directions: "Of a size that is less than normal or usual." },
            { id: 20, word: "Smart", media: "/aslMedia/word/Adjectives/smart.mp4", directions: "Having or showing a quick-witted intelligence." },
            { id: 21, word: "Tall", media: "/aslMedia/word/Adjectives/tall.mp4", directions: "Of great or more than average height." }
        ]
    },
    {
        id: 3, category: "Animals", words: [
            { id: 1, word: "Bird", media: "/aslMedia/word/Animals/bird.mp4", directions: "A warm-blooded egg-laying vertebrate distinguished by feathers and wings." },
            { id: 2, word: "Cat", media: "/aslMedia/word/Animals/cat.mp4", directions: "A small domesticated carnivorous mammal with soft fur and a short snout." },
            { id: 3, word: "Chicken", media: "/aslMedia/word/Animals/chicken.mp4", directions: "A domestic fowl kept for its eggs or meat." },
            { id: 4, word: "Dog", media: "/aslMedia/word/Animals/dog.mp4", directions: "A domesticated carnivorous mammal that typically has a long snout and an acute sense of smell." },
            { id: 5, word: "Fish", media: "/aslMedia/word/Animals/fish.mp4", directions: "A limbless cold-blooded vertebrate animal with gills and fins living wholly in wate" },
            { id: 6, word: "Horse", media: "/aslMedia/word/Animals/horse.mp4", directions: "A large plant-eating domesticated mammal with a flowing mane and tail." },
            { id: 7, word: "Lion", media: "/aslMedia/word/Animals/lion.mp4", directions: "A large tawny-colored cat that lives in prides, found in Africa and NW India." },
            { id: 8, word: "Monkey", media: "/aslMedia/word/Animals/monkey.mp4", directions: "A small to medium-sized primate that typically has a long tail and lives in trees." },
            { id: 9, word: "Mosquito", media: "/aslMedia/word/Animals/mosquito.mp4", directions: "A slender long-legged fly that sucks blood from animals and humans." },
            { id: 10, word: "Mouse", media: "/aslMedia/word/Animals/mouse.mp4", directions: "A small rodent that typically has a pointed snout, relatively large ears and eyes, and a long tail." },
            { id: 11, word: "Pig", media: "/aslMedia/word/Animals/pig.mp4", directions: "An omnivorous hoofed mammal with sparse bristly hair and a flat snout." },
            { id: 12, word: "Rabbit", media: "/aslMedia/word/Animals/rabbit.mp4", directions: "A burrowing, gregarious plant-eating mammal with long ears and a short tail." },
            { id: 13, word: "Tiger", media: "/aslMedia/word/Animals/tiger.mp4", directions: "A very large solitary cat with a yellow-brown coat striped with black." },
            { id: 14, word: "Whale", media: "/aslMedia/word/Animals/whale.mp4", directions: "A very large marine mammal with a blowhole on top of the head for breathing." }
        ]
    },
    {
        id: 4, category: "Color", words: [
            { id: 1, word: "Black", media: "/aslMedia/word/Color/black.mp4", directions: "The darkest color, the result of the absence or complete absorption of visible light." },
            { id: 2, word: "Blue", media: "/aslMedia/word/Color/blue.mp4", directions: "The color of the clear sky and the deep sea." },
            { id: 3, word: "Color", media: "/aslMedia/word/Color/color.mp4", directions: "The property possessed by an object of producing different sensations on the eye as a result of the way it reflects or emits light." },
            { id: 4, word: "Gray", media: "/aslMedia/word/Color/gray.mp4", directions: "A color intermediate between black and white." },
            { id: 5, word: "Green", media: "/aslMedia/word/Color/green.mp4", directions: "The color between blue and yellow in the spectrum; the color of growing grass." },
            { id: 6, word: "Orange", media: "/aslMedia/word/Color/orange.mp4", directions: "A bright reddish-yellow color like that of the skin of a certain citrus fruit." },
            { id: 7, word: "Pink", media: "/aslMedia/word/Color/pink.mp4", directions: "A pale red color." },
            { id: 8, word: "Purple", media: "/aslMedia/word/Color/purple.mp4", directions: "A color intermediate between red and blue." },
            { id: 9, word: "White", media: "/aslMedia/word/Color/white.mp4", directions: "The lightest color, the result of the reflection or transmission of all visible light." },
            { id: 10, word: "Yellow", media: "/aslMedia/word/Color/yellow.mp4", directions: "The color of ripe lemons or egg yolks." }
        ]
    },
    {
        id: 5, category: "Emergency", words: [
            { id: 1, word: "Accident", media: "/aslMedia/word/Emergency/accident.mp4", directions: "An unfortunate incident that happens unexpectedly and unintentionally." },
            { id: 2, word: "Aid", media: "/aslMedia/word/Emergency/aid.mp4", directions: "Help, typically of a practical nature." },
            { id: 3, word: "Alarm", media: "/aslMedia/word/Emergency/alarm.mp4", directions: "An anxious awareness of danger or a device that warns of it." },
            { id: 4, word: "Assist", media: "/aslMedia/word/Emergency/assist.mp4", directions: "To help someone, typically by doing a share of the work." },
            { id: 5, word: "Blood", media: "/aslMedia/word/Emergency/blood.mp4", directions: "The red liquid that circulates in the arteries and veins." },
            { id: 6, word: "Danger", media: "/aslMedia/word/Emergency/danger.mp4", directions: "The possibility of suffering harm or injury." },
            { id: 7, word: "Doctor", media: "/aslMedia/word/Emergency/doctor.mp4", directions: "A qualified practitioner of medicine." },
            { id: 8, word: "Earthquake", media: "/aslMedia/word/Emergency/earthquake.mp4", directions: "A sudden and violent shaking of the ground." },
            { id: 9, word: "Emergency", media: "/aslMedia/word/Emergency/emergency.mp4", directions: "A serious, unexpected, and often dangerous situation requiring immediate action." },
            { id: 10, word: "Fire", media: "/aslMedia/word/Emergency/fire.mp4", directions: "Combustion or burning, in which substances combine chemically with oxygen from the air." },
            { id: 11, word: "Flood", media: "/aslMedia/word/Emergency/flood.mp4", directions: "An overflow of a large amount of water beyond its normal confines." },
            { id: 12, word: "Help", media: "/aslMedia/word/Emergency/help.mp4", directions: "To make it easier for someone to do something by offering services or resources." },
            { id: 13, word: "Hurry", media: "/aslMedia/word/Emergency/hurry.mp4", directions: "To move or act with great haste." },
            { id: 14, word: "Hurt", media: "/aslMedia/word/Emergency/hurt.mp4", directions: "To cause physical pain or injury to." },
            { id: 15, word: "Light", media: "/aslMedia/word/Emergency/light.mp4", directions: "The natural agent that stimulates sight and makes things visible." },
            { id: 16, word: "Medicine", media: "/aslMedia/word/Emergency/medicine.mp4", directions: "A substance used in treating disease or relieving pain." },
            { id: 17, word: "Nurse", media: "/aslMedia/word/Emergency/nurse.mp4", directions: "A person trained to care for the sick or infirm." },
            { id: 18, word: "Pain", media: "/aslMedia/word/Emergency/pain.mp4", directions: "Physical suffering or discomfort caused by illness or injury." },
            { id: 19, word: "Police", media: "/aslMedia/word/Emergency/police.mp4", directions: "The civil force of a state, responsible for the prevention and detection of crime." },
            { id: 20, word: "Robber", media: "/aslMedia/word/Emergency/robber.mp4", directions: "A person who steals from a person or place by inappropriate force." },
            { id: 21, word: "Sick", media: "/aslMedia/word/Emergency/sick.mp4", directions: "Affected by physical or mental illness." },
            { id: 22, word: "Suspect", media: "/aslMedia/word/Emergency/suspect.mp4", directions: "A person thought to be guilty of a crime or offense." },
            { id: 23, word: "Wheelchair", media: "/aslMedia/word/Emergency/wheelchair.mp4", directions: "A chair fitted with wheels for use as a means of transport by a person who is unable to walk." }
        ]
    },
    {
        id: 6, category: "Family", words: [
            { id: 1, word: "Aunt", media: "/aslMedia/word/Family/aunt.mp4", directions: "The sister of one's father or mother." },
            { id: 2, word: "Baby", media: "/aslMedia/word/Family/baby.mp4", directions: "A very young child, especially one newly or recently born." },
            { id: 3, word: "Babysitter", media: "/aslMedia/word/Family/babysitter.mp4", directions: "A person who looks after a child or children while the parents are out." },
            { id: 4, word: "Boy", media: "/aslMedia/word/Family/boy.mp4", directions: "A male child or young man." },
            { id: 5, word: "Boyfriend", media: "/aslMedia/word/Family/boyfriend.mp4", directions: "A regular male companion with whom a person has a romantic or sexual relationship." },
            { id: 6, word: "Brother", media: "/aslMedia/word/Family/brother.mp4", directions: "A man or boy in relation to other sons and daughters of his parents." },
            { id: 7, word: "Cousin", media: "/aslMedia/word/Family/cousin.mp4", directions: "A child of one's uncle or aunt." },
            { id: 8, word: "Daughter", media: "/aslMedia/word/Family/daughter.mp4", directions: "A female offspring in relation to her parents." },
            { id: 9, word: "Family", media: "/aslMedia/word/Family/family.mp4", directions: "A group consisting of parents and children living together in a household." },
            { id: 10, word: "Father", media: "/aslMedia/word/Family/father.mp4", directions: "A male parent." },
            { id: 11, word: "Girlfriend", media: "/aslMedia/word/Family/girlfriend.mp4", directions: "A regular female companion with whom a person has a romantic or sexual relationship." },
            { id: 12, word: "Grandfather", media: "/aslMedia/word/Family/grandfather.mp4", directions: "The father of one's father or mother." },
            { id: 13, word: "Grandmother", media: "/aslMedia/word/Family/grandmother.mp4", directions: "The mother of one's father or mother." },
            { id: 14, word: "Jesus", media: "/aslMedia/word/Family/jesus.mp4", directions: "The central figure of the Christian religion." },
            { id: 15, word: "Lesbian", media: "/aslMedia/word/Family/lesbian.mp4", directions: "A woman who is romantically or sexually attracted to other women." },
            { id: 16, word: "Man", media: "/aslMedia/word/Family/man.mp4", directions: "An adult male human being." },
            { id: 17, word: "Mother", media: "/aslMedia/word/Family/mohter.mp4", directions: "A female parent." },
            { id: 18, word: "Nephew", media: "/aslMedia/word/Family/nephew.mp4", directions: "A son of one's brother or sister." },
            { id: 19, word: "Niece", media: "/aslMedia/word/Family/niece.mp4", directions: "A daughter of one's brother or sister." },
            { id: 20, word: "Senior", media: "/aslMedia/word/Family/senior.mp4", directions: "A person who is a certain amount of years older than another." },
            { id: 21, word: "Sister", media: "/aslMedia/word/Family/sister.mp4", directions: "A woman or girl in relation to other daughters and sons of her parents." },
            { id: 22, word: "Son", media: "/aslMedia/word/Family/son.mp4", directions: "A male offspring in relation to his parents." },
            { id: 23, word: "Uncle", media: "/aslMedia/word/Family/uncle.mp4", directions: "The brother of one's father or mother." },
            { id: 24, word: "Woman", media: "/aslMedia/word/Family/woman.mp4", directions: "An adult female human being." }
        ]
    },
    {
        id: 7, category: "General", words: [
            { id: 1, word: "Age", media: "/aslMedia/word/General/age.mp4", directions: "The length of time that a person or thing has existed." },
            { id: 2, word: "And", media: "/aslMedia/word/General/and.mp4", directions: "Used to connect words of the same part of speech, clauses, or sentences." },
            { id: 3, word: "Animal", media: "/aslMedia/word/General/animal.mp4", directions: "A living organism that feeds on organic matter." },
            { id: 4, word: "Birthday", media: "/aslMedia/word/General/birthday.mp4", directions: "The anniversary of the day on which a person was born." },
            { id: 5, word: "Bottle", media: "/aslMedia/word/General/bottle.mp4", directions: "A container, typically made of glass or plastic, with a narrow neck." },
            { id: 6, word: "Breakfast", media: "/aslMedia/word/General/breakfast.mp4", directions: "The first meal of the day." },
            { id: 7, word: "Bye", media: "/aslMedia/word/General/bye.mp4", directions: "A shortened version of goodbye; used when parting." },
            { id: 8, word: "Call", media: "/aslMedia/word/General/call.mp4", directions: "To contact someone by telephone." },
            { id: 9, word: "Chat", media: "/aslMedia/word/General/chat.mp4", directions: "To talk in a friendly and informal way." },
            { id: 10, word: "Close", media: "/aslMedia/word/General/close.mp4", directions: "To move something so as to cover an opening." },
            { id: 11, word: "Dinner", media: "/aslMedia/word/General/dinner.mp4", directions: "The main meal of the day, served in the evening." },
            { id: 12, word: "Door", media: "/aslMedia/word/General/door.mp4", directions: "A hinged or sliding barrier at the entrance to a building or room." },
            { id: 13, word: "Email", media: "/aslMedia/word/General/email.mp4", directions: "Messages distributed by electronic means from one computer user to another." },
            { id: 14, word: "Excuse", media: "/aslMedia/word/excuse.mp4", directions: "To seek to lessen the blame attaching to a fault or offense." },
            { id: 15, word: "First", media: "/aslMedia/word/General/first.mp4", directions: "Coming before all others in time or order." },
            { id: 16, word: "Food", media: "/aslMedia/word/General/food.mp4", directions: "Any nutritious substance that people or animals eat or drink." },
            { id: 17, word: "Goodbye", media: "/aslMedia/word/General/goodbye.mp4", directions: "Used to express good wishes when parting or at the end of a conversation." },
            { id: 18, word: "Hello", media: "/aslMedia/word/General/hello.mp4", directions: "Used as a greeting or to begin a telephone conversation." },
            { id: 19, word: "Look at", media: "/aslMedia/word/General/look at.mp4", directions: "To direct one's gaze toward someone or something." },
            { id: 20, word: "Look for", media: "/aslMedia/word/General/look for.mp4", directions: "To attempt to find someone or something." },
            { id: 21, word: "Lunch", media: "/aslMedia/word/General/lunch.mp4", directions: "A meal eaten in the middle of the day." },
            { id: 22, word: "Message", media: "/aslMedia/word/General/message.mp4", directions: "A short communication sent from one person to another." },
            { id: 23, word: "Next", media: "/aslMedia/word/General/next.mp4", directions: "Coming immediately after the present one in order or time." },
            { id: 24, word: "No", media: "/aslMedia/word/General/no.mp4", directions: "Used to give a negative response." },
            { id: 25, word: "Nothing", media: "/aslMedia/word/General/nothing.mp4", directions: "Not anything; no single thing." },
            { id: 26, word: "Open", media: "/aslMedia/word/General/open.mp4", directions: "To move something so as to allow access through an opening." },
            { id: 27, word: "Phone", media: "/aslMedia/word/General/phone.mp4", directions: "A device used for transmitting and receiving sound over long distances." },
            { id: 28, word: "Please", media: "/aslMedia/word/General/please.mp4", directions: "Used in polite requests or questions." },
            { id: 29, word: "Roof", media: "/aslMedia/word/General/roof.mp4", directions: "The structure forming the upper covering of a building or vehicle." },
            { id: 30, word: "Second", media: "/aslMedia/word/General/second.mp4", directions: "Coming after the first in time or order." },
            { id: 31, word: "Sorry", media: "/aslMedia/word/General/sorry.mp4", directions: "Feeling regret, compunction, or sorrow." },
            { id: 32, word: "Thank you", media: "/aslMedia/word/General/thank you.mp4", directions: "A polite expression used when acknowledging a gift, service, or compliment." },
            { id: 33, word: "Third", media: "/aslMedia/word/General/third.mp4", directions: "Coming after the second in time or order." },
            { id: 34, word: "Water", media: "/aslMedia/word/General/water.mp4", directions: "A colorless, transparent, odorless liquid that forms the seas, lakes, and rain." },
            { id: 35, word: "Welcome", media: "/aslMedia/word/General/welcome.mp4", directions: "Used to greet someone in a polite or friendly way." },
            { id: 36, word: "What", media: "/aslMedia/word/General/what.mp4", directions: "Asking for information specifying something." },
            { id: 37, word: "When", media: "/aslMedia/word/General/when.mp4", directions: "At what time or on what occasion." },
            { id: 14, word: "Where", media: "/aslMedia/word/General/where.mp4", directions: "In or to what place or position." },
            { id: 38, word: "Which", media: "/aslMedia/word/General/which.mp4", directions: "Asking for information specifying one or more people or things from a definite set." },
            { id: 39, word: "Who", media: "/aslMedia/word/General/who.mp4", directions: "Asking about which person or people." },
            { id: 40, word: "Why", media: "/aslMedia/word/General/why.mp4", directions: "For what reason or with what purpose." },
            { id: 41, word: "Window", media: "/aslMedia/word/General/window.mp4", directions: "An opening in a wall or door that is fitted with glass in a frame to admit light or air." },
            { id: 42, word: "Yes", media: "/aslMedia/word/General/yes.mp4", directions: "Used to give an affirmative response." },
            { id: 43, word: "Yourself", media: "/aslMedia/word/General/yourself.mp4", directions: "Used as the object of a verb or preposition to refer to the person being addressed." }
        ]
    },
    {
        id: 8, category: "Months", words: [
            { id: 1, word: "January", media: "/aslMedia/word/Months/january.mp4", directions: "" },
            { id: 2, word: "February", media: "/aslMedia/word/Months/february.mp4", directions: "" },
            { id: 3, word: "March", media: "/aslMedia/word/Months/march.mp4", directions: "" },
            { id: 4, word: "April", media: "/aslMedia/word/Months/april.mp4", directions: "" },
            { id: 5, word: "May", media: "/aslMedia/word/Months/may.mp4", directions: "" },
            { id: 6, word: "June", media: "/aslMedia/word/Months/june.mp4", directions: "" },
            { id: 7, word: "July", media: "/aslMedia/word/Months/july.mp4", directions: "" },
            { id: 8, word: "August", media: "/aslMedia/word/Months/august.mp4", directions: "" },
            { id: 9, word: "September", media: "/aslMedia/word/Months/september.mp4", directions: "" },
            { id: 10, word: "October", media: "/aslMedia/word/Months/october.mp4", directions: "" },
            { id: 11, word: "November", media: "/aslMedia/word/Months/november.mp4", directions: "" },
            { id: 12, word: "December", media: "/aslMedia/word/Months/december.mp4", directions: "" }
        ]
    },
    {
        id: 9, category: "Places", words: [
            { id: 1, word: "Above", media: "/aslMedia/word/Places/above.mp4", directions: "At a higher level or layer than." },
            { id: 2, word: "Africa", media: "/aslMedia/word/Places/africa.mp4", directions: "The second-largest continent in the world." },
            { id: 3, word: "America", media: "/aslMedia/word/Places/america.mp4", directions: "A large continent in the Western Hemisphere, or shorthand for the USA." },
            { id: 4, word: "Asia", media: "/aslMedia/word/Places/asia.mp4", directions: "The world's largest and most populous continent." },
            { id: 5, word: "Australia", media: "/aslMedia/word/Places/australia.mp4", directions: "A continent and country between the Indian and Pacific oceans." },
            { id: 6, word: "Austria", media: "/aslMedia/word/Places/austria.mp4", directions: "A landlocked country in Central Europe." },
            { id: 7, word: "Bank", media: "/aslMedia/word/Places/bank.mp4", directions: "A financial establishment that invests money and carries out other financial transactions." },
            { id: 8, word: "Bar", media: "/aslMedia/word/Places/bar.mp4", directions: "An establishment where alcohol and sometimes other refreshments are served." },
            { id: 9, word: "Basement", media: "/aslMedia/word/Places/basement.mp4", directions: "The floor of a building which is partly or entirely below ground level." },
            { id: 10, word: "Bathroom", media: "/aslMedia/word/Places/bathroom.mp4", directions: "A room containing a toilet and sink, and typically a bathtub or shower." },
            { id: 11, word: "Beside", media: "/aslMedia/word/Places/beside.mp4", directions: "At the side of; next to." },
            { id: 12, word: "Between", media: "/aslMedia/word/Places/between.mp4", directions: "In the space separating two objects or regions." },
            { id: 13, word: "Bookstore", media: "/aslMedia/word/Places/bookstore.mp4", directions: "A shop where books are sold." },
            { id: 14, word: "Bottom", media: "/aslMedia/word/Places/bottom.mp4", directions: "The lowest point or part of something." },
            { id: 15, word: "Church", media: "/aslMedia/word/Places/church.mp4", directions: "A building used for public Christian worship." },
            { id: 16, word: "East", media: "/aslMedia/word/Places/east.mp4", directions: "The direction toward the point of the horizon where the sun rises at the equinoxes." },
            { id: 17, word: "Home", media: "/aslMedia/word/Places/home.mp4", directions: "The place where one lives permanently, especially as a member of a family or household." },
            { id: 18, word: "House", media: "/aslMedia/word/Places/house.mp4", directions: "A building for human habitation, especially one that is lived in by a family or small group." },
            { id: 19, word: "Library", media: "/aslMedia/word/Places/library.mp4", directions: "A building or room containing collections of books and other periodicals for reading or borrowing." },
            { id: 20, word: "North", media: "/aslMedia/word/Places/north.mp4", directions: "The direction which is on the left of a person facing the rising sun." },
            { id: 21, word: "Place", media: "/aslMedia/word/Places/place.mp4", directions: "A particular position or point in space." },
            { id: 22, word: "Restuarant", media: "/aslMedia/word/Places/restaurant.mp4", directions: "A place where people pay to sit and eat meals that are cooked and served on the premises." },
            { id: 23, word: "School", media: "/aslMedia/word/Places/school.mp4", directions: "An institution for educating children." },
            { id: 24, word: "South", media: "/aslMedia/word/Places/south.mp4", directions: "The direction which is on the right of a person facing the rising sun." },
            { id: 25, word: "Store", media: "/aslMedia/word/Places/store.mp4", directions: "A shop of any size or kind." },
            { id: 26, word: "West", media: "/aslMedia/word/Places/west.mp4", directions: "The direction toward the point of the horizon where the sun sets at the equinoxes." },
            { id: 27, word: "Work", media: "/aslMedia/word/Places/work.mp4", directions: "Activity involving mental or physical effort done in order to achieve a purpose or result." },
            { id: 28, word: "Bedroom", media: "/aslMedia/word/Places/bedroom.mp4", directions: "A room used for sleeping in." }
        ]
    },
    {
        id: 10, category: "School", words: [
            { id: 1, word: "Chair", media: "/aslMedia/word/School/chair.mp4", directions: "A separate seat for one person, typically with a back and four legs." },
            { id: 2, word: "Classroom", media: "/aslMedia/word/School/classroom.mp4", directions: "A room, typically in a school, in which a class of students is taught." },
            { id: 3, word: "College", media: "/aslMedia/word/School/college.mp4", directions: "An educational institution or establishment, in particular one providing higher education." },
            { id: 4, word: "Elementary", media: "/aslMedia/word/School/elementary.mp4", directions: "Relating to the most rudimentary aspects of a subject or the first stage of formal education." },
            { id: 5, word: "Group", media: "/aslMedia/word/School/group.mp4", directions: "A number of people or things that are located close together or are considered or classed together." },
            { id: 6, word: "High School", media: "/aslMedia/word/School/high school.mp4", directions: "A school that typically comprises grades 7 through 12." },
            { id: 7, word: "Homework", media: "/aslMedia/word/School/homework.mp4", directions: "Schoolwork that a student is required to do at home." },
            { id: 8, word: "Laptop", media: "/aslMedia/word/School/laptop.mp4", directions: "A computer that is portable and suitable for use while traveling." },
            { id: 9, word: "Learn", media: "/aslMedia/word/School/learn.mp4", directions: "To acquire knowledge of or skill in something by study, experience, or being taught." },
            { id: 10, word: "Leave", media: "/aslMedia/word/School/leave.mp4", directions: "To go away from." },
            { id: 11, word: "Lesson", media: "/aslMedia/word/School/lesson.mp4", directions: "A period of learning or teaching." },
            { id: 12, word: "Listen", media: "/aslMedia/word/School/listen.mp4", directions: "To give one's attention to a sound." },
            { id: 13, word: "Pencil", media: "/aslMedia/word/School/pencil.mp4", directions: "An instrument for writing or drawing, consisting of a thin stick of graphite or similar material enclosed in a long thin piece of wood." },
            { id: 14, word: "Presentation", media: "/aslMedia/word/School/presentation.mp4", directions: "A speech or talk in which a new product, idea, or piece of work is shown and explained to an audience." },
            { id: 15, word: "Professor", media: "/aslMedia/word/School/professor.mp4", directions: "A teacher of the highest rank in a college or university." },
            { id: 16, word: "Project", media: "/aslMedia/word/School/project.mp4", directions: "An individual or collaborative enterprise that is carefully planned and designed to achieve a particular aim." },
            { id: 17, word: "Read", media: "/aslMedia/word/School/read.mp4", directions: "To look at and comprehend the meaning of written or printed matter." },
            { id: 18, word: "School", media: "/aslMedia/word/School/school.mp4", directions: "An institution for educating children or young adults." },
            { id: 19, word: "Student", media: "/aslMedia/word/School/student.mp4", directions: "A person who is studying at a school or college." },
            { id: 20, word: "Study", media: "/aslMedia/word/School/study.mp4", directions: "The devotion of time and attention to acquiring knowledge on an academic subject." },
            { id: 21, word: "Teach", media: "/aslMedia/word/School/teach.mp4", directions: "To impart knowledge to or instruct someone as to how to do something." },
            { id: 22, word: "Teacher", media: "/aslMedia/word/School/teacher.mp4", directions: "A person who teaches, especially in a school." },
            { id: 23, word: "Work", media: "/aslMedia/word/School/work.mp4", directions: "To exert oneself by doing mental or physical effort for a purpose." },
            { id: 24, word: "Write", media: "/aslMedia/word/School/write.mp4", directions: "To mark letters, words, or other symbols on a surface, typically paper, with a pen, pencil, or similar implement." }
        ]
    },
    {
        id: 11, category: "Time", words: [
            { id: 1, word: "After", media: "/aslMedia/word/Time/after.mp4", directions: "During the period of time following an event." },
            { id: 2, word: "Afternoon", media: "/aslMedia/word/Time/afternoon.mp4", directions: "The time from noon or lunchtime to evening." },
            { id: 3, word: "Before", media: "/aslMedia/word/Time/before.mp4", directions: "During the period of time preceding a particular event or time." },
            { id: 4, word: "Date", media: "/aslMedia/word/Time/date.mp4", directions: "The day of the month or year as specified by a number." },
            { id: 5, word: "Day", media: "/aslMedia/word/Time/day.mp4", directions: "A period of twenty-four hours as a unit of time." },
            { id: 6, word: "Evening", media: "/aslMedia/word/Time/evening.mp4", directions: "The period of time at the end of the day, usually from about 6 p.m. to bedtime." },
            { id: 7, word: "Future", media: "/aslMedia/word/Time/future.mp4", directions: "A period of time following the moment of speaking or writing." },
            { id: 8, word: "Hour", media: "/aslMedia/word/Time/hour.mp4", directions: "A period of time equal to a twenty-fourth part of a day and night and divided into 60 minutes." },
            { id: 9, word: "Minute", media: "/aslMedia/word/Time/minute.mp4", directions: "A period of time equal to sixty seconds or a sixtieth of an hour." },
            { id: 10, word: "Morning", media: "/aslMedia/word/Time/morning.mp4", directions: "The period of time between dawn and noon." },
            { id: 11, word: "Night", media: "/aslMedia/word/Time/night.mp4", directions: "The period from sunset to sunrise in each twenty-four hours." },
            { id: 12, word: "Now", media: "/aslMedia/word/Time/now.mp4", directions: "At the present time or moment." },
            { id: 13, word: "Past", media: "/aslMedia/word/Time/past.mp4", directions: "The time or a period of time before the moment of speaking or writing." },
            { id: 14, word: "Present", media: "/aslMedia/word/Time/present.mp4", directions: "Existing or occurring now." },
            { id: 15, word: "Second", media: "/aslMedia/word/Time/second.mp4", directions: "An unit of time equal to one sixtieth of a minute." },
            { id: 16, word: "Time", media: "/aslMedia/word/Time/time.mp4", directions: "The indefinite continued progress of existence and events in the past, present, and future." },
            { id: 17, word: "Today", media: "/aslMedia/word/Time/today.mp4", directions: "On or during this present day." },
            { id: 18, word: "Tomorrow", media: "/aslMedia/word/Time/tomorrow.mp4", directions: "On or during the day after today." },
            { id: 19, word: "While", media: "/aslMedia/word/Time/while.mp4", directions: "A period of time." },
            { id: 20, word: "Yesterday", media: "/aslMedia/word/Time/yesterday.mp4", directions: "On or during the day before today." }
        ]
    }
]