{/* 
    These data will be used by the frontend
    to get and load specific words/alphabets
    to be displayed in the dictionary tab and used in the learn tab
*/}
export const ALPHABET_DICT = [
    { id: 1, category: "Alphabet", word: "A", media: "/aslMedia/alphabet/A.png", directions: "Make a fist with your thumb straight up against the side of your index finger." },
    { id: 2, category: "Alphabet", word: "B", media: "</aslMedia/alphabet/B.png>", directions: "Flatten your hand with fingers together and thumb tucked across the palm." },
    { id: 3, category: "Alphabet", word: "C", media: "</aslMedia/alphabet/C.png>", directions: "Curve your hand into a C shape, as if gripping a thick glass." },
    { id: 4, category: "Alphabet", word: "D", media: "</aslMedia/alphabet/D.png>", directions: "Point your index finger up; touch your thumb to the tips of your middle, ring, and pinky fingers to form a circle." },
    { id: 5, category: "Alphabet", word: "E", media: "</aslMedia/alphabet/E.png>", directions: "Tuck all four fingers down and pull your thumb in tight under them (looks like a claw)." },
    { id: 6, category: "Alphabet", word: "F", media: "</aslMedia/alphabet/F.png>", directions: "Touch your index finger and thumb together (like an OK sign); keep the other three fingers spread and pointing up." },
    { id: 7, category: "Alphabet", word: "G", media: "</aslMedia/alphabet/G.png>", directions: "Point your index finger and thumb sideways, parallel to each other, like you are measuring something tiny." },
    { id: 8, category: "Alphabet", word: "H", media: "</aslMedia/alphabet/H.png>", directions: "Point your index and middle fingers sideways together; tuck the rest." },
    { id: 9, category: "Alphabet", word: "I", media: "</aslMedia/alphabet/I.png>", directions: "Make a fist but stick your pinky finger straight up." },
    { id: 10, category: "Alphabet", word: "J", media: "</aslMedia/alphabet/J.png>", directions: "Start with the \"I\" position and trace a \"J\" curve in the air with your pinky." },
    { id: 11, category: "Alphabet", word: "K", media: "</aslMedia/alphabet/K.png>", directions: "Point your index finger up; put your thumb on the middle of your middle finger, which is angled slightly forward." },
    { id: 12, category: "Alphabet", word: "L", media: "</aslMedia/alphabet/L.png>", directions: "Make an \"L\" shape with your index finger pointing up and your thumb pointing sideways." },
    { id: 13, category: "Alphabet", word: "M", media: "</aslMedia/alphabet/M.png>", directions: "Make a fist and tuck your thumb under your index, middle, and ring fingers." },
    { id: 14, category: "Alphabet", word: "N", media: "</aslMedia/alphabet/N.png>", directions: "Make a fist and tuck your thumb under your index and middle fingers." },
    { id: 15, category: "Alphabet", word: "O", media: "</aslMedia/alphabet/O.png>", directions: "Touch all your fingertips to your thumb to form a circle." },
    { id: 16, category: "Alphabet", word: "P", media: "</aslMedia/alphabet/P.png>", directions: "Like a \"K\", but pointed downward. Index finger points at the floor, thumb on the middle finger." },
    { id: 17, category: "Alphabet", word: "Q", media: "</aslMedia/alphabet/Q.png>", directions: "Like a \"G\", but pointed downward. Your index and thumb \"pinch\" toward the floor." },
    { id: 18, category: "Alphabet", word: "R", media: "</aslMedia/alphabet/R.png>", directions: "Cross your middle finger over your index finger (like a \"good luck\" gesture)." },
    { id: 19, category: "Alphabet", word: "S", media: "</aslMedia/alphabet/S.png>", directions: "Make a solid fist with your thumb tucked across the front of all your fingers." },
    { id: 20, category: "Alphabet", word: "T", media: "</aslMedia/alphabet/T.png>", directions: "Make a fist and tuck your thumb between your index and middle finger." },
    { id: 21, category: "Alphabet", word: "U", media: "</aslMedia/alphabet/U.png>", directions: "Point your index and middle fingers straight up, pressed together." },
    { id: 22, category: "Alphabet", word: "V", media: "</aslMedia/alphabet/V.png>", directions: "Point your index and middle fingers up and spread them apart (like a \"Peace\" sign)." },
    { id: 23, category: "Alphabet", word: "W", media: "</aslMedia/alphabet/W.png>", directions: "Point your index, middle, and ring fingers up and spread them out (forming a \"W\")." },
    { id: 24, category: "Alphabet", word: "X", media: "</aslMedia/alphabet/X.png>", directions: "Make a fist, then hook your index finger like a pirate's hook." },
    { id: 25, category: "Alphabet", word: "Y", media: "</aslMedia/alphabet/Y.png>", directions: "Stick your thumb and pinky out wide; keep the middle three fingers tucked into the palm." },
    { id: 26, category: "Alphabet", word: "Z", media: "</aslMedia/alphabet/Z.png>", directions: "Use your index finger to \"draw\" the letter Z in the air." },
]

export const WORD_DICT = [
    {
        id: 1, category: "Actions", words: [
            { id: 1, word: "Accept", media: "</aslMedia/word/>", directions: "" },
            { id: 2, word: "Action", media: "</aslMedia/word/>", directions: "" },
            { id: 3, word: "Add", media: "</aslMedia/word/>", directions: "" },
            { id: 4, word: "Admire", media: "</aslMedia/word/>", directions: "" },
            { id: 5, word: "Affect", media: "</aslMedia/word/>", directions: "" },
            { id: 6, word: "Allow", media: "</aslMedia/word/>", directions: "" },
            { id: 7, word: "Approach", media: "</aslMedia/word/>", directions: "" },
            { id: 8, word: "Arrive", media: "</aslMedia/word/>", directions: "" },
            { id: 9, word: "Ask", media: "</aslMedia/word/>", directions: "" },
            { id: 10, word: "Avoid", media: "</aslMedia/word/>", directions: "" },
            { id: 11, word: "Believe", media: "</aslMedia/word/>", directions: "" },
            { id: 12, word: "Eat", media: "</aslMedia/word/>", directions: "" },
            { id: 13, word: "Fall in love", media: "</aslMedia/word/>", directions: "" },
            { id: 14, word: "Give", media: "</aslMedia/word/>", directions: "" },
            { id: 15, word: "Love", media: "</aslMedia/word/>", directions: "" },
            { id: 16, word: "Pray", media: "</aslMedia/word/>", directions: "" },
            { id: 17, word: "Receive", media: "</aslMedia/word/>", directions: "" },
            { id: 18, word: "Run", media: "</aslMedia/word/>", directions: "" },
            { id: 19, word: "Shower", media: "</aslMedia/word/>", directions: "" },
            { id: 20, word: "Sleep", media: "</aslMedia/word/>", directions: "" },
            { id: 21, word: "Wake up", media: "</aslMedia/word/>", directions: "" },
            { id: 22, word: "Walk", media: "</aslMedia/word/>", directions: "" }
        ]
    },
    {
        id: 2, category: "Adjectives", words: [
            { id: 1, word: "Afraid", media: "</aslMedia/word/>", directions: "" },
            { id: 2, word: "Amazing", media: "</aslMedia/word/>", directions: "" },
            { id: 3, word: "Bad", media: "</aslMedia/word/>", directions: "" },
            { id: 4, word: "Beautiful", media: "</aslMedia/word/>", directions: "" },
            { id: 5, word: "Best", media: "</aslMedia/word/>", directions: "" },
            { id: 6, word: "Better", media: "</aslMedia/word/>", directions: "" },
            { id: 7, word: "Big", media: "</aslMedia/word/>", directions: "" },
            { id: 8, word: "Cold", media: "</aslMedia/word/>", directions: "" },
            { id: 9, word: "Dumb", media: "</aslMedia/word/>", directions: "" },
            { id: 10, word: "Fast", media: "</aslMedia/word/>", directions: "" },
            { id: 11, word: "Hot", media: "</aslMedia/word/>", directions: "" },
            { id: 12, word: "Long", media: "</aslMedia/word/>", directions: "" },
            { id: 13, word: "Loud", media: "</aslMedia/word/>", directions: "" },
            { id: 14, word: "Lucky", media: "</aslMedia/word/>", directions: "" },
            { id: 15, word: "Quiet", media: "</aslMedia/word/>", directions: "" },
            { id: 16, word: "See", media: "</aslMedia/word/>", directions: "" },
            { id: 17, word: "Short", media: "</aslMedia/word/>", directions: "" },
            { id: 18, word: "Slow", media: "</aslMedia/word/>", directions: "" },
            { id: 19, word: "Small", media: "</aslMedia/word/>", directions: "" },
            { id: 20, word: "Smart", media: "</aslMedia/word/>", directions: "" },
            { id: 21, word: "Tall", media: "</aslMedia/word/>", directions: "" }
        ]
    },
    {
        id: 3, category: "Animals", words: [
            { id: 1, word: "Bird", media: "</aslMedia/word/>", directions: "" },
            { id: 2, word: "Cat", media: "</aslMedia/word/>", directions: "" },
            { id: 3, word: "Chicken", media: "</aslMedia/word/>", directions: "" },
            { id: 4, word: "Dog", media: "</aslMedia/word/>", directions: "" },
            { id: 5, word: "Fish", media: "</aslMedia/word/>", directions: "" },
            { id: 6, word: "Horse", media: "</aslMedia/word/>", directions: "" },
            { id: 7, word: "Lion", media: "</aslMedia/word/>", directions: "" },
            { id: 8, word: "Monkey", media: "</aslMedia/word/>", directions: "" },
            { id: 9, word: "Mosquito", media: "</aslMedia/word/>", directions: "" },
            { id: 10, word: "Mouse", media: "</aslMedia/word/>", directions: "" },
            { id: 11, word: "Pig", media: "</aslMedia/word/>", directions: "" },
            { id: 12, word: "Rabbit", media: "</aslMedia/word/>", directions: "" },
            { id: 13, word: "Tiger", media: "</aslMedia/word/>", directions: "" },
            { id: 14, word: "Whale", media: "</aslMedia/word/>", directions: "" }
        ]
    },
    {
        id: 4, category: "Color", words: [
            { id: 1, word: "Black", media: "</aslMedia/word/>", directions: "" },
            { id: 2, word: "Blue", media: "</aslMedia/word/>", directions: "" },
            { id: 3, word: "Color", media: "</aslMedia/word/>", directions: "" },
            { id: 4, word: "Gray", media: "</aslMedia/word/>", directions: "" },
            { id: 5, word: "Green", media: "</aslMedia/word/>", directions: "" },
            { id: 6, word: "Orange", media: "</aslMedia/word/>", directions: "" },
            { id: 7, word: "Pink", media: "</aslMedia/word/>", directions: "" },
            { id: 8, word: "Purple", media: "</aslMedia/word/>", directions: "" },
            { id: 9, word: "White", media: "</aslMedia/word/>", directions: "" },
            { id: 10, word: "Yellow", media: "</aslMedia/word/>", directions: "" }
        ]
    },
    {
        id: 5, category: "Emergency", words: [
            { id: 1, word: "Accident", media: "</aslMedia/word/>", directions: "" },
            { id: 2, word: "Aid", media: "</aslMedia/word/>", directions: "" },
            { id: 3, word: "Alarm", media: "</aslMedia/word/>", directions: "" },
            { id: 4, word: "Assist", media: "</aslMedia/word/>", directions: "" },
            { id: 5, word: "Blood", media: "</aslMedia/word/>", directions: "" },
            { id: 6, word: "Danger", media: "</aslMedia/word/>", directions: "" },
            { id: 7, word: "Doctor", media: "</aslMedia/word/>", directions: "" },
            { id: 8, word: "Earthquake", media: "</aslMedia/word/>", directions: "" },
            { id: 9, word: "Emergency", media: "</aslMedia/word/>", directions: "" },
            { id: 10, word: "Fire", media: "</aslMedia/word/>", directions: "" },
            { id: 11, word: "Flood", media: "</aslMedia/word/>", directions: "" },
            { id: 12, word: "Help", media: "</aslMedia/word/>", directions: "" },
            { id: 13, word: "Hurry", media: "</aslMedia/word/>", directions: "" },
            { id: 14, word: "Hurt", media: "</aslMedia/word/>", directions: "" },
            { id: 15, word: "Light", media: "</aslMedia/word/>", directions: "" },
            { id: 16, word: "Medicine", media: "</aslMedia/word/>", directions: "" },
            { id: 17, word: "Nurse", media: "</aslMedia/word/>", directions: "" },
            { id: 18, word: "Pain", media: "</aslMedia/word/>", directions: "" },
            { id: 19, word: "Police", media: "</aslMedia/word/>", directions: "" },
            { id: 20, word: "Robber", media: "</aslMedia/word/>", directions: "" },
            { id: 21, word: "Sick", media: "</aslMedia/word/>", directions: "" },
            { id: 22, word: "Suspect", media: "</aslMedia/word/>", directions: "" },
            { id: 23, word: "Wheelchair", media: "</aslMedia/word/>", directions: "" }
        ]
    },
    {
        id: 6, category: "Family", words: [
            { id: 1, word: "Aunt", media: "</aslMedia/word/>", directions: "" },
            { id: 2, word: "Baby", media: "</aslMedia/word/>", directions: "" },
            { id: 3, word: "Babysitter", media: "</aslMedia/word/>", directions: "" },
            { id: 4, word: "Boy", media: "</aslMedia/word/>", directions: "" },
            { id: 5, word: "Boyfriend", media: "</aslMedia/word/>", directions: "" },
            { id: 6, word: "Brother", media: "</aslMedia/word/>", directions: "" },
            { id: 7, word: "Cousin", media: "</aslMedia/word/>", directions: "" },
            { id: 8, word: "Daughter", media: "</aslMedia/word/>", directions: "" },
            { id: 9, word: "Family", media: "</aslMedia/word/>", directions: "" },
            { id: 10, word: "Father", media: "</aslMedia/word/>", directions: "" },
            { id: 11, word: "Girlfriend", media: "</aslMedia/word/>", directions: "" },
            { id: 12, word: "Grandfather", media: "</aslMedia/word/>", directions: "" },
            { id: 13, word: "Grandmother", media: "</aslMedia/word/>", directions: "" },
            { id: 14, word: "Jesus", media: "</aslMedia/word/>", directions: "" },
            { id: 15, word: "Lesbian", media: "</aslMedia/word/>", directions: "" },
            { id: 16, word: "Man", media: "</aslMedia/word/>", directions: "" },
            { id: 17, word: "Mother", media: "</aslMedia/word/>", directions: "" },
            { id: 18, word: "Nephew", media: "</aslMedia/word/>", directions: "" },
            { id: 19, word: "Niece", media: "</aslMedia/word/>", directions: "" },
            { id: 20, word: "Senior", media: "</aslMedia/word/>", directions: "" },
            { id: 21, word: "Sister", media: "</aslMedia/word/>", directions: "" },
            { id: 22, word: "Son", media: "</aslMedia/word/>", directions: "" },
            { id: 23, word: "Uncle", media: "</aslMedia/word/>", directions: "" },
            { id: 24, word: "Woman", media: "</aslMedia/word/>", directions: "" }
        ]
    },
    {
        id: 7, category: "General", words: [
            { id: 1, word: "Age", media: "</aslMedia/word/>", directions: "" },
            { id: 2, word: "And", media: "</aslMedia/word/>", directions: "" },
            { id: 3, word: "Animal", media: "</aslMedia/word/>", directions: "" },
            { id: 4, word: "Birthday", media: "</aslMedia/word/>", directions: "" },
            { id: 5, word: "Bottle", media: "</aslMedia/word/>", directions: "" },
            { id: 6, word: "Breakfast", media: "</aslMedia/word/>", directions: "" },
            { id: 7, word: "Bye", media: "</aslMedia/word/>", directions: "" },
            { id: 8, word: "Call", media: "</aslMedia/word/>", directions: "" },
            { id: 9, word: "Chat", media: "</aslMedia/word/>", directions: "" },
            { id: 10, word: "Close", media: "</aslMedia/word/>", directions: "" },
            { id: 11, word: "Dinner", media: "</aslMedia/word/>", directions: "" },
            { id: 12, word: "Door", media: "</aslMedia/word/>", directions: "" },
            { id: 13, word: "Email", media: "</aslMedia/word/>", directions: "" },
            { id: 14, word: "Excuse", media: "</aslMedia/word/>", directions: "" },
            { id: 15, word: "First", media: "</aslMedia/word/>", directions: "" },
            { id: 16, word: "Food", media: "</aslMedia/word/>", directions: "" },
            { id: 17, word: "Goodbye", media: "</aslMedia/word/>", directions: "" },
            { id: 18, word: "Hello", media: "</aslMedia/word/>", directions: "" },
            { id: 19, word: "Look at", media: "</aslMedia/word/>", directions: "" },
            { id: 20, word: "Look for", media: "</aslMedia/word/>", directions: "" },
            { id: 21, word: "Lunch", media: "</aslMedia/word/>", directions: "" },
            { id: 22, word: "Message", media: "</aslMedia/word/>", directions: "" },
            { id: 23, word: "Next", media: "</aslMedia/word/>", directions: "" },
            { id: 24, word: "No", media: "</aslMedia/word/>", directions: "" },
            { id: 25, word: "Nothing", media: "</aslMedia/word/>", directions: "" },
            { id: 26, word: "Open", media: "</aslMedia/word/>", directions: "" },
            { id: 27, word: "Phone", media: "</aslMedia/word/>", directions: "" },
            { id: 28, word: "Please", media: "</aslMedia/word/>", directions: "" },
            { id: 29, word: "Roof", media: "</aslMedia/word/>", directions: "" },
            { id: 30, word: "Second", media: "</aslMedia/word/>", directions: "" },
            { id: 31, word: "Sorry", media: "</aslMedia/word/>", directions: "" },
            { id: 32, word: "Thank you", media: "</aslMedia/word/>", directions: "" },
            { id: 33, word: "Third", media: "</aslMedia/word/>", directions: "" },
            { id: 34, word: "Water", media: "</aslMedia/word/>", directions: "" },
            { id: 35, word: "Welcome", media: "</aslMedia/word/>", directions: "" },
            { id: 36, word: "What", media: "</aslMedia/word/>", directions: "" },
            { id: 37, word: "When", media: "</aslMedia/word/>", directions: "" },
            { id: 14, word: "Where", media: "</aslMedia/word/>", directions: "" },
            { id: 38, word: "Which", media: "</aslMedia/word/>", directions: "" },
            { id: 39, word: "Who", media: "</aslMedia/word/>", directions: "" },
            { id: 40, word: "Why", media: "</aslMedia/word/>", directions: "" },
            { id: 41, word: "Window", media: "</aslMedia/word/>", directions: "" },
            { id: 42, word: "Yes", media: "</aslMedia/word/>", directions: "" },
            { id: 43, word: "Yourself", media: "</aslMedia/word/>", directions: "" }
        ]
    },
    {
        id: 8, category: "Months", words: [
            { id: 1, word: "January", media: "</aslMedia/word/>", directions: "" },
            { id: 2, word: "February", media: "</aslMedia/word/>", directions: "" },
            { id: 3, word: "March", media: "</aslMedia/word/>", directions: "" },
            { id: 4, word: "April", media: "</aslMedia/word/>", directions: "" },
            { id: 5, word: "May", media: "</aslMedia/word/>", directions: "" },
            { id: 6, word: "June", media: "</aslMedia/word/>", directions: "" },
            { id: 7, word: "July", media: "</aslMedia/word/>", directions: "" },
            { id: 8, word: "August", media: "</aslMedia/word/>", directions: "" },
            { id: 9, word: "September", media: "</aslMedia/word/>", directions: "" },
            { id: 10, word: "October", media: "</aslMedia/word/>", directions: "" },
            { id: 11, word: "November", media: "</aslMedia/word/>", directions: "" },
            { id: 12, word: "December", media: "</aslMedia/word/>", directions: "" }
        ]
    },
    {
        id: 9, category: "Places", words: [
            { id: 1, word: "Above", media: "</aslMedia/word/>", directions: "" },
            { id: 2, word: "Africa", media: "</aslMedia/word/>", directions: "" },
            { id: 3, word: "America", media: "</aslMedia/word/>", directions: "" },
            { id: 4, word: "Asia", media: "</aslMedia/word/>", directions: "" },
            { id: 5, word: "Australia", media: "</aslMedia/word/>", directions: "" },
            { id: 6, word: "Austria", media: "</aslMedia/word/>", directions: "" },
            { id: 7, word: "Bank", media: "</aslMedia/word/>", directions: "" },
            { id: 8, word: "Bar", media: "</aslMedia/word/>", directions: "" },
            { id: 9, word: "Basement", media: "</aslMedia/word/>", directions: "" },
            { id: 10, word: "Bathroom", media: "</aslMedia/word/>", directions: "" },
            { id: 11, word: "Beside", media: "</aslMedia/word/>", directions: "" },
            { id: 12, word: "Between", media: "</aslMedia/word/>", directions: "" },
            { id: 13, word: "Bookstore", media: "</aslMedia/word/>", directions: "" },
            { id: 14, word: "Bottom", media: "</aslMedia/word/>", directions: "" },
            { id: 15, word: "Church", media: "</aslMedia/word/>", directions: "" },
            { id: 16, word: "East", media: "</aslMedia/word/>", directions: "" },
            { id: 17, word: "Home", media: "</aslMedia/word/>", directions: "" },
            { id: 18, word: "House", media: "</aslMedia/word/>", directions: "" },
            { id: 19, word: "Library", media: "</aslMedia/word/>", directions: "" },
            { id: 20, word: "North", media: "</aslMedia/word/>", directions: "" },
            { id: 21, word: "Place", media: "</aslMedia/word/>", directions: "" },
            { id: 22, word: "Restuarant", media: "</aslMedia/word/>", directions: "" },
            { id: 23, word: "School", media: "</aslMedia/word/>", directions: "" },
            { id: 24, word: "South", media: "</aslMedia/word/>", directions: "" },
            { id: 25, word: "Store", media: "</aslMedia/word/>", directions: "" },
            { id: 26, word: "West", media: "</aslMedia/word/>", directions: "" },
            { id: 27, word: "Work", media: "</aslMedia/word/>", directions: "" },
            { id: 28, word: "Bedroom", media: "</aslMedia/word/>", directions: "" }
        ]
    },
    {
        id: 10, category: "School", words: [
            { id: 1, word: "Chair", media: "</aslMedia/word/>", directions: "" },
            { id: 2, word: "Classroom", media: "</aslMedia/word/>", directions: "" },
            { id: 3, word: "College", media: "</aslMedia/word/>", directions: "" },
            { id: 4, word: "Elementary", media: "</aslMedia/word/>", directions: "" },
            { id: 5, word: "Group", media: "</aslMedia/word/>", directions: "" },
            { id: 6, word: "High School", media: "</aslMedia/word/>", directions: "" },
            { id: 7, word: "Homework", media: "</aslMedia/word/>", directions: "" },
            { id: 8, word: "Laptop", media: "</aslMedia/word/>", directions: "" },
            { id: 9, word: "Learn", media: "</aslMedia/word/>", directions: "" },
            { id: 10, word: "Leave", media: "</aslMedia/word/>", directions: "" },
            { id: 11, word: "Lesson", media: "</aslMedia/word/>", directions: "" },
            { id: 12, word: "Listen", media: "</aslMedia/word/>", directions: "" },
            { id: 13, word: "Pencil", media: "</aslMedia/word/>", directions: "" },
            { id: 14, word: "Presentation", media: "</aslMedia/word/>", directions: "" },
            { id: 15, word: "Professor", media: "</aslMedia/word/>", directions: "" },
            { id: 16, word: "Project", media: "</aslMedia/word/>", directions: "" },
            { id: 17, word: "Read", media: "</aslMedia/word/>", directions: "" },
            { id: 18, word: "School", media: "</aslMedia/word/>", directions: "" },
            { id: 19, word: "Student", media: "</aslMedia/word/>", directions: "" },
            { id: 20, word: "Study", media: "</aslMedia/word/>", directions: "" },
            { id: 21, word: "Teach", media: "</aslMedia/word/>", directions: "" },
            { id: 22, word: "Teacher", media: "</aslMedia/word/>", directions: "" },
            { id: 23, word: "Work", media: "</aslMedia/word/>", directions: "" },
            { id: 24, word: "Write", media: "</aslMedia/word/>", directions: "" }
        ]
    },
    {
        id: 11, category: "Time", words: [
            { id: 1, word: "After", media: "</aslMedia/word/>", directions: "" },
            { id: 2, word: "Afternoon", media: "</aslMedia/word/>", directions: "" },
            { id: 3, word: "Before", media: "</aslMedia/word/>", directions: "" },
            { id: 4, word: "Date", media: "</aslMedia/word/>", directions: "" },
            { id: 5, word: "Day", media: "</aslMedia/word/>", directions: "" },
            { id: 6, word: "Evening", media: "</aslMedia/word/>", directions: "" },
            { id: 7, word: "Future", media: "</aslMedia/word/>", directions: "" },
            { id: 8, word: "Hour", media: "</aslMedia/word/>", directions: "" },
            { id: 9, word: "Minute", media: "</aslMedia/word/>", directions: "" },
            { id: 10, word: "Morning", media: "</aslMedia/word/>", directions: "" },
            { id: 11, word: "Night", media: "</aslMedia/word/>", directions: "" },
            { id: 12, word: "Now", media: "</aslMedia/word/>", directions: "" },
            { id: 13, word: "Past", media: "</aslMedia/word/>", directions: "" },
            { id: 14, word: "Present", media: "</aslMedia/word/>", directions: "" },
            { id: 15, word: "Second", media: "</aslMedia/word/>", directions: "" },
            { id: 16, word: "Time", media: "</aslMedia/word/>", directions: "" },
            { id: 17, word: "Today", media: "</aslMedia/word/>", directions: "" },
            { id: 18, word: "Tomorrow", media: "</aslMedia/word/>", directions: "" },
            { id: 19, word: "While", media: "</aslMedia/word/>", directions: "" },
            { id: 20, word: "Yesterday", media: "</aslMedia/word/>", directions: "" }
        ]
    }
]