{/* 
    These data will be used by the frontend
    to get and load specific words/alphabets
    to be displayed in the dictionary tab and used in the learn tab
*/}
export const ALPHABET_DICT = [
    { id: 1, category: "Alphabet", word: "A", media: "<path_to_img>", directions: "" },
    { id: 2, category: "Alphabet", word: "B", media: "<path_to_img>", directions: "" },
    { id: 3, category: "Alphabet", word: "C", media: "<path_to_img>", directions: "" },
    { id: 4, category: "Alphabet", word: "D", media: "<path_to_img>", directions: "" },
    { id: 5, category: "Alphabet", word: "E", media: "<path_to_img>", directions: "" },
    { id: 6, category: "Alphabet", word: "F", media: "<path_to_img>", directions: "" },
    { id: 7, category: "Alphabet", word: "G", media: "<path_to_img>", directions: "" },
    { id: 8, category: "Alphabet", word: "H", media: "<path_to_img>", directions: "" },
    { id: 9, category: "Alphabet", word: "I", media: "<path_to_img>", directions: "" },
    { id: 10, category: "Alphabet", word: "J", media: "<path_to_img>", directions: "" },
    { id: 11, category: "Alphabet", word: "K", media: "<path_to_img>", directions: "" },
    { id: 12, category: "Alphabet", word: "L", media: "<path_to_img>", directions: "" },
    { id: 13, category: "Alphabet", word: "M", media: "<path_to_img>", directions: "" },
    { id: 14, category: "Alphabet", word: "N", media: "<path_to_img>", directions: "" },
    { id: 15, category: "Alphabet", word: "O", media: "<path_to_img>", directions: "" },
    { id: 16, category: "Alphabet", word: "P", media: "<path_to_img>", directions: "" },
    { id: 17, category: "Alphabet", word: "Q", media: "<path_to_img>", directions: "" },
    { id: 18, category: "Alphabet", word: "R", media: "<path_to_img>", directions: "" },
    { id: 19, category: "Alphabet", word: "S", media: "<path_to_img>", directions: "" },
    { id: 20, category: "Alphabet", word: "T", media: "<path_to_img>", directions: "" },
    { id: 21, category: "Alphabet", word: "U", media: "<path_to_img>", directions: "" },
    { id: 22, category: "Alphabet", word: "V", media: "<path_to_img>", directions: "" },
    { id: 23, category: "Alphabet", word: "W", media: "<path_to_img>", directions: "" },
    { id: 24, category: "Alphabet", word: "X", media: "<path_to_img>", directions: "" },
    { id: 25, category: "Alphabet", word: "Y", media: "<path_to_img>", directions: "" },
    { id: 26, category: "Alphabet", word: "Z", media: "<path_to_img>", directions: "" },
]

export const WORD_DICT = [
    {
        id: 1, category: "Actions", words: [
            { id: 1, word: "Accept", media: "<path_to_vid>", directions: "" },
            { id: 2, word: "Action", media: "<path_to_vid>", directions: "" },
            { id: 3, word: "Add", media: "<path_to_vid>", directions: "" },
            { id: 4, word: "Admire", media: "<path_to_vid>", directions: "" },
            { id: 5, word: "Affect", media: "<path_to_vid>", directions: "" },
            { id: 6, word: "Allow", media: "<path_to_vid>", directions: "" },
            { id: 7, word: "Approach", media: "<path_to_vid>", directions: "" },
            { id: 8, word: "Arrive", media: "<path_to_vid>", directions: "" },
            { id: 9, word: "Ask", media: "<path_to_vid>", directions: "" },
            { id: 10, word: "Avoid", media: "<path_to_vid>", directions: "" },
            { id: 11, word: "Believe", media: "<path_to_vid>", directions: "" },
            { id: 12, word: "Eat", media: "<path_to_vid>", directions: "" },
            { id: 13, word: "Fall in love", media: "<path_to_vid>", directions: "" },
            { id: 14, word: "Give", media: "<path_to_vid>", directions: "" },
            { id: 15, word: "Love", media: "<path_to_vid>", directions: "" },
            { id: 16, word: "Pray", media: "<path_to_vid>", directions: "" },
            { id: 17, word: "Receive", media: "<path_to_vid>", directions: "" },
            { id: 18, word: "Run", media: "<path_to_vid>", directions: "" },
            { id: 19, word: "Shower", media: "<path_to_vid>", directions: "" },
            { id: 20, word: "Sleep", media: "<path_to_vid>", directions: "" },
            { id: 21, word: "Wake up", media: "<path_to_vid>", directions: "" },
            { id: 22, word: "Walk", media: "<path_to_vid>", directions: "" }
        ]
    },
    {
        id: 2, category: "Adjectives", words: [
            { id: 1, word: "Afraid", media: "<path_to_vid>", directions: "" },
            { id: 2, word: "Amazing", media: "<path_to_vid>", directions: "" },
            { id: 3, word: "Bad", media: "<path_to_vid>", directions: "" },
            { id: 4, word: "Beautiful", media: "<path_to_vid>", directions: "" },
            { id: 5, word: "Best", media: "<path_to_vid>", directions: "" },
            { id: 6, word: "Better", media: "<path_to_vid>", directions: "" },
            { id: 7, word: "Big", media: "<path_to_vid>", directions: "" },
            { id: 8, word: "Cold", media: "<path_to_vid>", directions: "" },
            { id: 9, word: "Dumb", media: "<path_to_vid>", directions: "" },
            { id: 10, word: "Fast", media: "<path_to_vid>", directions: "" },
            { id: 11, word: "Hot", media: "<path_to_vid>", directions: "" },
            { id: 12, word: "Long", media: "<path_to_vid>", directions: "" },
            { id: 13, word: "Loud", media: "<path_to_vid>", directions: "" },
            { id: 14, word: "Lucky", media: "<path_to_vid>", directions: "" },
            { id: 15, word: "Quiet", media: "<path_to_vid>", directions: "" },
            { id: 16, word: "See", media: "<path_to_vid>", directions: "" },
            { id: 17, word: "Short", media: "<path_to_vid>", directions: "" },
            { id: 18, word: "Slow", media: "<path_to_vid>", directions: "" },
            { id: 19, word: "Small", media: "<path_to_vid>", directions: "" },
            { id: 20, word: "Smart", media: "<path_to_vid>", directions: "" },
            { id: 21, word: "Tall", media: "<path_to_vid>", directions: "" }
        ]
    },
    {
        id: 3, category: "Animals", words: [
            { id: 1, word: "Bird", media: "<path_to_vid>", directions: "" },
            { id: 2, word: "Cat", media: "<path_to_vid>", directions: "" },
            { id: 3, word: "Chicken", media: "<path_to_vid>", directions: "" },
            { id: 4, word: "Dog", media: "<path_to_vid>", directions: "" },
            { id: 5, word: "Fish", media: "<path_to_vid>", directions: "" },
            { id: 6, word: "Horse", media: "<path_to_vid>", directions: "" },
            { id: 7, word: "Lion", media: "<path_to_vid>", directions: "" },
            { id: 8, word: "Monkey", media: "<path_to_vid>", directions: "" },
            { id: 9, word: "Mosquito", media: "<path_to_vid>", directions: "" },
            { id: 10, word: "Mouse", media: "<path_to_vid>", directions: "" },
            { id: 11, word: "Pig", media: "<path_to_vid>", directions: "" },
            { id: 12, word: "Rabbit", media: "<path_to_vid>", directions: "" },
            { id: 13, word: "Tiger", media: "<path_to_vid>", directions: "" },
            { id: 14, word: "Whale", media: "<path_to_vid>", directions: "" }
        ]
    },
    {
        id: 4, category: "Color", words: [
            { id: 1, word: "Black", media: "<path_to_vid>", directions: "" },
            { id: 2, word: "Blue", media: "<path_to_vid>", directions: "" },
            { id: 3, word: "Color", media: "<path_to_vid>", directions: "" },
            { id: 4, word: "Gray", media: "<path_to_vid>", directions: "" },
            { id: 5, word: "Green", media: "<path_to_vid>", directions: "" },
            { id: 6, word: "Orange", media: "<path_to_vid>", directions: "" },
            { id: 7, word: "Pink", media: "<path_to_vid>", directions: "" },
            { id: 8, word: "Purple", media: "<path_to_vid>", directions: "" },
            { id: 9, word: "White", media: "<path_to_vid>", directions: "" },
            { id: 10, word: "Yellow", media: "<path_to_vid>", directions: "" }
        ]
    },
    {
        id: 5, category: "Emergency", words: [
            { id: 1, word: "Accident", media: "<path_to_vid>", directions: "" },
            { id: 2, word: "Aid", media: "<path_to_vid>", directions: "" },
            { id: 3, word: "Alarm", media: "<path_to_vid>", directions: "" },
            { id: 4, word: "Assist", media: "<path_to_vid>", directions: "" },
            { id: 5, word: "Blood", media: "<path_to_vid>", directions: "" },
            { id: 6, word: "Danger", media: "<path_to_vid>", directions: "" },
            { id: 7, word: "Doctor", media: "<path_to_vid>", directions: "" },
            { id: 8, word: "Earthquake", media: "<path_to_vid>", directions: "" },
            { id: 9, word: "Emergency", media: "<path_to_vid>", directions: "" },
            { id: 10, word: "Fire", media: "<path_to_vid>", directions: "" },
            { id: 11, word: "Flood", media: "<path_to_vid>", directions: "" },
            { id: 12, word: "Help", media: "<path_to_vid>", directions: "" },
            { id: 13, word: "Hurry", media: "<path_to_vid>", directions: "" },
            { id: 14, word: "Hurt", media: "<path_to_vid>", directions: "" },
            { id: 15, word: "Light", media: "<path_to_vid>", directions: "" },
            { id: 16, word: "Medicine", media: "<path_to_vid>", directions: "" },
            { id: 17, word: "Nurse", media: "<path_to_vid>", directions: "" },
            { id: 18, word: "Pain", media: "<path_to_vid>", directions: "" },
            { id: 19, word: "Police", media: "<path_to_vid>", directions: "" },
            { id: 20, word: "Robber", media: "<path_to_vid>", directions: "" },
            { id: 21, word: "Sick", media: "<path_to_vid>", directions: "" },
            { id: 22, word: "Suspect", media: "<path_to_vid>", directions: "" },
            { id: 23, word: "Wheelchair", media: "<path_to_vid>", directions: "" }
        ]
    },
    {
        id: 6, category: "Family", words: [
            { id: 1, word: "Aunt", media: "<path_to_vid>", directions: "" },
            { id: 2, word: "Baby", media: "<path_to_vid>", directions: "" },
            { id: 3, word: "Babysitter", media: "<path_to_vid>", directions: "" },
            { id: 4, word: "Boy", media: "<path_to_vid>", directions: "" },
            { id: 5, word: "Boyfriend", media: "<path_to_vid>", directions: "" },
            { id: 6, word: "Brother", media: "<path_to_vid>", directions: "" },
            { id: 7, word: "Cousin", media: "<path_to_vid>", directions: "" },
            { id: 8, word: "Daughter", media: "<path_to_vid>", directions: "" },
            { id: 9, word: "Family", media: "<path_to_vid>", directions: "" },
            { id: 10, word: "Father", media: "<path_to_vid>", directions: "" },
            { id: 11, word: "Girlfriend", media: "<path_to_vid>", directions: "" },
            { id: 12, word: "Grandfather", media: "<path_to_vid>", directions: "" },
            { id: 13, word: "Grandmother", media: "<path_to_vid>", directions: "" },
            { id: 14, word: "Jesus", media: "<path_to_vid>", directions: "" },
            { id: 15, word: "Lesbian", media: "<path_to_vid>", directions: "" },
            { id: 16, word: "Man", media: "<path_to_vid>", directions: "" },
            { id: 17, word: "Mother", media: "<path_to_vid>", directions: "" },
            { id: 18, word: "Nephew", media: "<path_to_vid>", directions: "" },
            { id: 19, word: "Niece", media: "<path_to_vid>", directions: "" },
            { id: 20, word: "Senior", media: "<path_to_vid>", directions: "" },
            { id: 21, word: "Sister", media: "<path_to_vid>", directions: "" },
            { id: 22, word: "Son", media: "<path_to_vid>", directions: "" },
            { id: 23, word: "Uncle", media: "<path_to_vid>", directions: "" },
            { id: 24, word: "Woman", media: "<path_to_vid>", directions: "" }
        ]
    },
    {
        id: 7, category: "General", words: [
            { id: 1, word: "Age", media: "<path_to_vid>", directions: "" },
            { id: 2, word: "And", media: "<path_to_vid>", directions: "" },
            { id: 3, word: "Animal", media: "<path_to_vid>", directions: "" },
            { id: 4, word: "Birthday", media: "<path_to_vid>", directions: "" },
            { id: 5, word: "Bottle", media: "<path_to_vid>", directions: "" },
            { id: 6, word: "Breakfast", media: "<path_to_vid>", directions: "" },
            { id: 7, word: "Bye", media: "<path_to_vid>", directions: "" },
            { id: 8, word: "Call", media: "<path_to_vid>", directions: "" },
            { id: 9, word: "Chat", media: "<path_to_vid>", directions: "" },
            { id: 10, word: "Close", media: "<path_to_vid>", directions: "" },
            { id: 11, word: "Dinner", media: "<path_to_vid>", directions: "" },
            { id: 12, word: "Door", media: "<path_to_vid>", directions: "" },
            { id: 13, word: "Email", media: "<path_to_vid>", directions: "" },
            { id: 14, word: "Excuse", media: "<path_to_vid>", directions: "" },
            { id: 15, word: "First", media: "<path_to_vid>", directions: "" },
            { id: 16, word: "Food", media: "<path_to_vid>", directions: "" },
            { id: 17, word: "Goodbye", media: "<path_to_vid>", directions: "" },
            { id: 18, word: "Hello", media: "<path_to_vid>", directions: "" },
            { id: 19, word: "Look at", media: "<path_to_vid>", directions: "" },
            { id: 20, word: "Look for", media: "<path_to_vid>", directions: "" },
            { id: 21, word: "Lunch", media: "<path_to_vid>", directions: "" },
            { id: 22, word: "Message", media: "<path_to_vid>", directions: "" },
            { id: 23, word: "Next", media: "<path_to_vid>", directions: "" },
            { id: 24, word: "No", media: "<path_to_vid>", directions: "" },
            { id: 25, word: "Nothing", media: "<path_to_vid>", directions: "" },
            { id: 26, word: "Open", media: "<path_to_vid>", directions: "" },
            { id: 27, word: "Phone", media: "<path_to_vid>", directions: "" },
            { id: 28, word: "Please", media: "<path_to_vid>", directions: "" },
            { id: 29, word: "Roof", media: "<path_to_vid>", directions: "" },
            { id: 30, word: "Second", media: "<path_to_vid>", directions: "" },
            { id: 31, word: "Sorry", media: "<path_to_vid>", directions: "" },
            { id: 32, word: "Thank you", media: "<path_to_vid>", directions: "" },
            { id: 33, word: "Third", media: "<path_to_vid>", directions: "" },
            { id: 34, word: "Water", media: "<path_to_vid>", directions: "" },
            { id: 35, word: "Welcome", media: "<path_to_vid>", directions: "" },
            { id: 36, word: "What", media: "<path_to_vid>", directions: "" },
            { id: 37, word: "When", media: "<path_to_vid>", directions: "" },
            { id: 14, word: "Where", media: "<path_to_vid>", directions: "" },
            { id: 38, word: "Which", media: "<path_to_vid>", directions: "" },
            { id: 39, word: "Who", media: "<path_to_vid>", directions: "" },
            { id: 40, word: "Why", media: "<path_to_vid>", directions: "" },
            { id: 41, word: "Window", media: "<path_to_vid>", directions: "" },
            { id: 42, word: "Yes", media: "<path_to_vid>", directions: "" },
            { id: 43, word: "Yourself", media: "<path_to_vid>", directions: "" }
        ]
    },
    {
        id: 8, category: "Months", words: [
            { id: 1, word: "January", media: "<path_to_vid>", directions: "" },
            { id: 2, word: "February", media: "<path_to_vid>", directions: "" },
            { id: 3, word: "March", media: "<path_to_vid>", directions: "" },
            { id: 4, word: "April", media: "<path_to_vid>", directions: "" },
            { id: 5, word: "May", media: "<path_to_vid>", directions: "" },
            { id: 6, word: "June", media: "<path_to_vid>", directions: "" },
            { id: 7, word: "July", media: "<path_to_vid>", directions: "" },
            { id: 8, word: "August", media: "<path_to_vid>", directions: "" },
            { id: 9, word: "September", media: "<path_to_vid>", directions: "" },
            { id: 10, word: "October", media: "<path_to_vid>", directions: "" },
            { id: 11, word: "November", media: "<path_to_vid>", directions: "" },
            { id: 12, word: "December", media: "<path_to_vid>", directions: "" }
        ]
    },
    {
        id: 9, category: "Places", words: [
            { id: 1, word: "Above", media: "<path_to_vid>", directions: "" },
            { id: 2, word: "Africa", media: "<path_to_vid>", directions: "" },
            { id: 3, word: "America", media: "<path_to_vid>", directions: "" },
            { id: 4, word: "Asia", media: "<path_to_vid>", directions: "" },
            { id: 5, word: "Australia", media: "<path_to_vid>", directions: "" },
            { id: 6, word: "Austria", media: "<path_to_vid>", directions: "" },
            { id: 7, word: "Bank", media: "<path_to_vid>", directions: "" },
            { id: 8, word: "Bar", media: "<path_to_vid>", directions: "" },
            { id: 9, word: "Basement", media: "<path_to_vid>", directions: "" },
            { id: 10, word: "Bathroom", media: "<path_to_vid>", directions: "" },
            { id: 11, word: "Beside", media: "<path_to_vid>", directions: "" },
            { id: 12, word: "Between", media: "<path_to_vid>", directions: "" },
            { id: 13, word: "Bookstore", media: "<path_to_vid>", directions: "" },
            { id: 14, word: "Bottom", media: "<path_to_vid>", directions: "" },
            { id: 15, word: "Church", media: "<path_to_vid>", directions: "" },
            { id: 16, word: "East", media: "<path_to_vid>", directions: "" },
            { id: 17, word: "Home", media: "<path_to_vid>", directions: "" },
            { id: 18, word: "House", media: "<path_to_vid>", directions: "" },
            { id: 19, word: "Library", media: "<path_to_vid>", directions: "" },
            { id: 20, word: "North", media: "<path_to_vid>", directions: "" },
            { id: 21, word: "Place", media: "<path_to_vid>", directions: "" },
            { id: 22, word: "Restuarant", media: "<path_to_vid>", directions: "" },
            { id: 23, word: "School", media: "<path_to_vid>", directions: "" },
            { id: 24, word: "South", media: "<path_to_vid>", directions: "" },
            { id: 25, word: "Store", media: "<path_to_vid>", directions: "" },
            { id: 26, word: "West", media: "<path_to_vid>", directions: "" },
            { id: 27, word: "Work", media: "<path_to_vid>", directions: "" },
            { id: 28, word: "Bedroom", media: "<path_to_vid>", directions: "" }
        ]
    },
    {
        id: 10, category: "School", words: [
            { id: 1, word: "Chair", media: "<path_to_vid>", directions: "" },
            { id: 2, word: "Classroom", media: "<path_to_vid>", directions: "" },
            { id: 3, word: "College", media: "<path_to_vid>", directions: "" },
            { id: 4, word: "Elementary", media: "<path_to_vid>", directions: "" },
            { id: 5, word: "Group", media: "<path_to_vid>", directions: "" },
            { id: 6, word: "High School", media: "<path_to_vid>", directions: "" },
            { id: 7, word: "Homework", media: "<path_to_vid>", directions: "" },
            { id: 8, word: "Laptop", media: "<path_to_vid>", directions: "" },
            { id: 9, word: "Learn", media: "<path_to_vid>", directions: "" },
            { id: 10, word: "Leave", media: "<path_to_vid>", directions: "" },
            { id: 11, word: "Lesson", media: "<path_to_vid>", directions: "" },
            { id: 12, word: "Listen", media: "<path_to_vid>", directions: "" },
            { id: 13, word: "Pencil", media: "<path_to_vid>", directions: "" },
            { id: 14, word: "Presentation", media: "<path_to_vid>", directions: "" },
            { id: 15, word: "Professor", media: "<path_to_vid>", directions: "" },
            { id: 16, word: "Project", media: "<path_to_vid>", directions: "" },
            { id: 17, word: "Read", media: "<path_to_vid>", directions: "" },
            { id: 18, word: "School", media: "<path_to_vid>", directions: "" },
            { id: 19, word: "Student", media: "<path_to_vid>", directions: "" },
            { id: 20, word: "Study", media: "<path_to_vid>", directions: "" },
            { id: 21, word: "Teach", media: "<path_to_vid>", directions: "" },
            { id: 22, word: "Teacher", media: "<path_to_vid>", directions: "" },
            { id: 23, word: "Work", media: "<path_to_vid>", directions: "" },
            { id: 24, word: "Write", media: "<path_to_vid>", directions: "" }
        ]
    },
    {
        id: 11, category: "Time", words: [
            { id: 1, word: "After", media: "<path_to_vid>", directions: "" },
            { id: 2, word: "Afternoon", media: "<path_to_vid>", directions: "" },
            { id: 3, word: "Before", media: "<path_to_vid>", directions: "" },
            { id: 4, word: "Date", media: "<path_to_vid>", directions: "" },
            { id: 5, word: "Day", media: "<path_to_vid>", directions: "" },
            { id: 6, word: "Evening", media: "<path_to_vid>", directions: "" },
            { id: 7, word: "Future", media: "<path_to_vid>", directions: "" },
            { id: 8, word: "Hour", media: "<path_to_vid>", directions: "" },
            { id: 9, word: "Minute", media: "<path_to_vid>", directions: "" },
            { id: 10, word: "Morning", media: "<path_to_vid>", directions: "" },
            { id: 11, word: "Night", media: "<path_to_vid>", directions: "" },
            { id: 12, word: "Now", media: "<path_to_vid>", directions: "" },
            { id: 13, word: "Past", media: "<path_to_vid>", directions: "" },
            { id: 14, word: "Present", media: "<path_to_vid>", directions: "" },
            { id: 15, word: "Second", media: "<path_to_vid>", directions: "" },
            { id: 16, word: "Time", media: "<path_to_vid>", directions: "" },
            { id: 17, word: "Today", media: "<path_to_vid>", directions: "" },
            { id: 18, word: "Tomorrow", media: "<path_to_vid>", directions: "" },
            { id: 19, word: "While", media: "<path_to_vid>", directions: "" },
            { id: 20, word: "Yesterday", media: "<path_to_vid>", directions: "" }
        ]
    }
]